/* COSMOS KIDS — content model.
   Single source of truth for bodies, levels, missions, comparisons and UI copy.
   Bilingual values are {fr, en}. Nothing here is presentational.
   Loaded as a classic script -> window.COSMOS_DATA (also exported for bundlers). */
(function (root) {
  const T = (fr, en) => ({ fr, en });

  /* ---------- scale levels (§6) ---------- */
  const LEVELS = [
    { n: 1, id: 'earth',    name: T('Terre', 'Earth'),                   scale: T('~400 000 km', '~400,000 km') },
    { n: 2, id: 'solar',    name: T('Système solaire', 'Solar System'),   scale: T('~9 milliards km', '~9 billion km') },
    { n: 3, id: 'stellar',  name: T('Voisinage solaire', 'Solar Neighbourhood'), scale: T('~20 années-lumière', '~20 light-years') },
    { n: 4, id: 'galaxy',   name: T('Voie lactée', 'Milky Way'),          scale: T('~100 000 années-lumière', '~100,000 light-years') },
    { n: 5, id: 'local',    name: T('Groupe local', 'Local Group'),       scale: T('~10 millions années-lumière', '~10 million light-years') },
    { n: 6, id: 'universe', name: T('Univers observable', 'Observable Universe'), scale: T('~93 milliards années-lumière', '~93 billion light-years') }
  ];

  /* ---------- bodies ----------
     radius / orbit are SCENE units (see cosmos-stage.js), not physical.
     Physical truth lives in `stats`. `simplified` flags an exaggerated scale. */
  const BODIES = [
    {
      id: 'earth', level: 1, kind: 'planet', glyph: '🌍', name: T('Terre', 'Earth'),
      sub: T('Planète rocheuse — notre maison', 'Rocky planet — our home'),
      color: '#3f8fd6', texture: 'earth', radius: 6.2, rotation: 0.06, atmosphere: '#5fa8ff',
      parent: 'sun', orbit: { a: 150, period: 365, tilt: 0 },
      stats: [
        { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('150 millions km', '150 million km') },
        { label: T('Diamètre', 'Diameter'), value: T('12 742 km', '12,742 km') },
        { label: T('Température moyenne', 'Average temperature'), value: T('15 °C', '15 °C') },
        { label: T('Lunes', 'Moons'), value: T('1 — la Lune', '1 — the Moon') },
        { label: T('Durée du jour', 'Day length'), value: T('23 h 56 min', '23 h 56 min') },
        { label: T('Durée de l’année', 'Year length'), value: T('365,25 jours', '365.25 days') }
      ],
      fact: T('Vue depuis la Lune, la Terre tient derrière ton pouce tendu.',
              'Seen from the Moon, Earth hides behind your outstretched thumb.'),
      explain: {
        simple: T('La Terre est la seule planète connue où l’eau liquide couvre presque toute la surface.',
                  'Earth is the only known planet where liquid water covers almost the whole surface.'),
        curious: T('Son noyau de fer en rotation crée un champ magnétique qui dévie le vent solaire et protège l’atmosphère.',
                   'Its spinning iron core creates a magnetic field that deflects the solar wind and protects the atmosphere.'),
        expert: T('Masse 5,972×10²⁴ kg. Albédo moyen 0,30. Atmosphère à 78 % N₂ / 21 % O₂, effet de serre net ≈ +33 °C.',
                  'Mass 5.972×10²⁴ kg. Mean albedo 0.30. Atmosphere 78% N₂ / 21% O₂, net greenhouse ≈ +33 °C.')
      }
    },
    {
      id: 'moon', level: 1, kind: 'moon', glyph: '🌕', name: T('Lune', 'Moon'),
      sub: T('Satellite naturel de la Terre', 'Earth’s natural satellite'),
      color: '#b9b6ae', texture: 'rock', radius: 1.7, rotation: 0.01,
      parent: 'earth', orbit: { a: 26, period: 27.3, tilt: 5.1 },
      stats: [
        { label: T('Distance de la Terre', 'Distance from Earth'), value: T('384 400 km', '384,400 km') },
        { label: T('Diamètre', 'Diameter'), value: T('3 474 km', '3,474 km') },
        { label: T('Gravité', 'Gravity'), value: T('1/6 de la Terre', '1/6 of Earth’s') },
        { label: T('Temps de la lumière', 'Light travel time'), value: T('1,3 seconde', '1.3 seconds') }
      ],
      fact: T('La Lune s’éloigne de nous de 3,8 cm par an, l’épaisseur de deux doigts.',
              'The Moon drifts 3.8 cm further away every year — about two fingers wide.'),
      explain: {
        simple: T('La Lune ne brille pas : elle reflète la lumière du Soleil.', 'The Moon does not shine: it reflects sunlight.'),
        curious: T('Elle tourne sur elle-même exactement en un tour d’orbite, alors on voit toujours la même face.',
                   'It spins once per orbit, so we always see the same face.'),
        expert: T('Rotation synchrone par verrouillage de marée. Libration ±7,9° en longitude.',
                  'Tidally locked synchronous rotation. Libration of ±7.9° in longitude.')
      }
    },
    {
      id: 'iss', level: 1, kind: 'station', glyph: '🛰', name: T('ISS', 'ISS'),
      sub: T('Station spatiale internationale', 'International Space Station'),
      color: '#dfe8f5', texture: 'metal', radius: 0.35, parent: 'earth', orbit: { a: 8.4, period: 0.064, tilt: 51.6 },
      stats: [
        { label: T('Altitude', 'Altitude'), value: T('≈ 408 km', '≈ 408 km') },
        { label: T('Vitesse', 'Speed'), value: T('27 600 km/h', '27,600 km/h') },
        { label: T('Un tour de Terre', 'One orbit'), value: T('92 minutes', '92 minutes') },
        { label: T('Habitants', 'Crew'), value: T('7 en général', 'usually 7') }
      ],
      fact: T('À bord, l’équipage voit 16 levers de soleil par jour.', 'On board, the crew sees 16 sunrises a day.'),
      explain: {
        simple: T('C’est une maison qui tourne autour de la Terre, avec des gens dedans.', 'It is a house orbiting Earth, with people inside.'),
        curious: T('Elle tombe en permanence vers la Terre, mais si vite de côté qu’elle la rate toujours.',
                   'It falls towards Earth constantly, but moves sideways so fast it always misses.'),
        expert: T('Orbite terrestre basse, inclinaison 51,64°. Réajustements réguliers contre la traînée atmosphérique.',
                  'Low Earth orbit, 51.64° inclination. Regular reboosts counter atmospheric drag.')
      }
    },

    { id: 'sun', level: 2, kind: 'star', glyph: '☀️', name: T('Soleil', 'Sun'),
      sub: T('Étoile naine jaune — type G', 'Yellow dwarf star — type G'),
      color: '#ffcf6b', texture: 'sun', radius: 16, emissive: true, rotation: 0.004,
      stats: [
        { label: T('Diamètre', 'Diameter'), value: T('1 392 000 km', '1,392,000 km') },
        { label: T('Température de surface', 'Surface temperature'), value: T('5 500 °C', '5,500 °C') },
        { label: T('Cœur', 'Core'), value: T('15 millions °C', '15 million °C') },
        { label: T('Âge', 'Age'), value: T('4,6 milliards d’années', '4.6 billion years') },
        { label: T('Temps de la lumière', 'Light travel time'), value: T('8 min 20 s', '8 min 20 s') }
      ],
      fact: T('Un million de Terres tiendraient à l’intérieur du Soleil.', 'A million Earths would fit inside the Sun.'),
      explain: {
        simple: T('Le Soleil est une énorme boule de gaz brûlant qui donne lumière et chaleur.', 'The Sun is a huge ball of burning gas that gives light and heat.'),
        curious: T('En son cœur, l’hydrogène fusionne en hélium et libère l’énergie qui met 100 000 ans à ressortir.',
                   'In its core, hydrogen fuses into helium, releasing energy that takes 100,000 years to escape.'),
        expert: T('Fusion p-p, 3,8×10²⁶ W. Masse 1,989×10³⁰ kg, 99,86 % de la masse du Système solaire.',
                  'p-p chain fusion, 3.8×10²⁶ W. Mass 1.989×10³⁰ kg — 99.86% of the Solar System.')
      } },
    { id: 'mercury', level: 2, kind: 'planet', glyph: '☿', name: T('Mercure', 'Mercury'), sub: T('Planète rocheuse', 'Rocky planet'),
      color: '#9a8f86', texture: 'rock', radius: 2.2, parent: 'sun', orbit: { a: 58, period: 88 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('58 millions km', '58 million km') },
               { label: T('Diamètre', 'Diameter'), value: T('4 879 km', '4,879 km') },
               { label: T('Températures', 'Temperatures'), value: T('-180 °C à +430 °C', '-180 °C to +430 °C') },
               { label: T('Durée de l’année', 'Year length'), value: T('88 jours', '88 days') } ],
      fact: T('Une journée sur Mercure dure deux de ses années.', 'A day on Mercury lasts two of its years.'),
      explain: { simple: T('C’est la plus petite planète et la plus proche du Soleil.', 'It is the smallest planet and the closest to the Sun.'),
                 curious: T('Sans atmosphère pour garder la chaleur, elle passe de la fournaise au congélateur.', 'With no atmosphere to hold heat, it swings from furnace to freezer.'),
                 expert: T('Résonance spin-orbite 3:2. Excentricité 0,206, la plus forte des planètes.', '3:2 spin–orbit resonance. Eccentricity 0.206, highest of the planets.') } },
    { id: 'venus', level: 2, kind: 'planet', glyph: '♀', name: T('Vénus', 'Venus'), sub: T('Planète rocheuse', 'Rocky planet'),
      color: '#e8c98d', texture: 'cloud', radius: 5.9, parent: 'sun', orbit: { a: 108, period: 225 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('108 millions km', '108 million km') },
               { label: T('Diamètre', 'Diameter'), value: T('12 104 km', '12,104 km') },
               { label: T('Température moyenne', 'Average temperature'), value: T('465 °C', '465 °C') },
               { label: T('Pression', 'Pressure'), value: T('92× la Terre', '92× Earth') } ],
      fact: T('Vénus tourne à l’envers : le Soleil s’y lève à l’ouest.', 'Venus spins backwards: the Sun rises in the west.'),
      explain: { simple: T('Vénus est la planète la plus chaude, à cause de ses nuages épais.', 'Venus is the hottest planet because of its thick clouds.'),
                 curious: T('Son atmosphère de CO₂ piège la chaleur : un effet de serre emballé.', 'Its CO₂ atmosphere traps heat — a runaway greenhouse effect.'),
                 expert: T('Rotation rétrograde, période 243 j. Nuages de H₂SO₄, albédo 0,77.', 'Retrograde rotation, 243-day period. H₂SO₄ clouds, albedo 0.77.') } },
    { id: 'mars', level: 2, kind: 'planet', glyph: '🔴', name: T('Mars', 'Mars'), sub: T('Planète rocheuse', 'Rocky planet'),
      color: '#c1543a', texture: 'rock', radius: 3.3, parent: 'sun', orbit: { a: 228, period: 687 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('228 millions km', '228 million km') },
               { label: T('Diamètre', 'Diameter'), value: T('6 779 km', '6,779 km') },
               { label: T('Température moyenne', 'Average temperature'), value: T('-63 °C', '-63 °C') },
               { label: T('Lunes', 'Moons'), value: T('2 — Phobos, Deimos', '2 — Phobos, Deimos') },
               { label: T('Durée du jour', 'Day length'), value: T('24 h 37 min', '24 h 37 min') } ],
      fact: T('Mars abrite Olympus Mons, un volcan trois fois plus haut que l’Everest.', 'Mars has Olympus Mons, a volcano three times taller than Everest.'),
      explain: { simple: T('Mars est rouge parce que son sol est couvert de rouille.', 'Mars is red because its soil is covered in rust.'),
                 curious: T('L’oxyde de fer de la poussière donne la couleur ; des tempêtes peuvent couvrir la planète entière.', 'Iron oxide dust gives the colour; storms can cover the whole planet.'),
                 expert: T('Atmosphère 95 % CO₂, 6 mbar. Gravité 3,71 m/s². Calottes de CO₂ et H₂O.', 'Atmosphere 95% CO₂ at 6 mbar. Gravity 3.71 m/s². CO₂ and H₂O polar caps.') } },
    { id: 'jupiter', level: 2, kind: 'planet', glyph: '🟠', name: T('Jupiter', 'Jupiter'), sub: T('Géante gazeuse', 'Gas giant'),
      color: '#d9a06a', texture: 'bands', radius: 11.5, parent: 'sun', orbit: { a: 300, period: 4333 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('778 millions km', '778 million km') },
               { label: T('Diamètre', 'Diameter'), value: T('139 820 km', '139,820 km') },
               { label: T('Température moyenne', 'Average temperature'), value: T('-145 °C', '-145 °C') },
               { label: T('Lunes connues', 'Known moons'), value: T('95', '95') },
               { label: T('Durée du jour', 'Day length'), value: T('9 h 56 min', '9 h 56 min') } ],
      fact: T('Jupiter pourrait contenir environ 1 300 Terres.', 'Jupiter could hold about 1,300 Earths.'),
      explain: { simple: T('Jupiter est la plus grande planète : une boule de gaz sans sol.', 'Jupiter is the largest planet: a ball of gas with no ground.'),
                 curious: T('Sa Grande Tache Rouge est une tempête plus large que la Terre, active depuis des siècles.', 'Its Great Red Spot is a storm wider than Earth, raging for centuries.'),
                 expert: T('Masse 1,898×10²⁷ kg. Magnétosphère 20 000× celle de la Terre.', 'Mass 1.898×10²⁷ kg. Magnetosphere 20,000× Earth’s.') } },
    { id: 'saturn', level: 2, kind: 'planet', glyph: '🪐', name: T('Saturne', 'Saturn'), sub: T('Planète gazeuse', 'Gas planet'),
      color: '#e3c88f', texture: 'bands', radius: 9.8, ring: { inner: 13, outer: 21, color: '#d8c39a' },
      parent: 'sun', orbit: { a: 380, period: 10759 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('1,43 milliard km', '1.43 billion km') },
               { label: T('Diamètre', 'Diameter'), value: T('116 460 km', '116,460 km') },
               { label: T('Température moyenne', 'Average temperature'), value: T('-178 °C', '-178 °C') },
               { label: T('Lunes connues', 'Known moons'), value: T('plus de 100', 'more than 100') },
               { label: T('Durée du jour', 'Day length'), value: T('10 h 33 min', '10 h 33 min') },
               { label: T('Durée de l’année', 'Year length'), value: T('29 années terrestres', '29 Earth years') } ],
      fact: T('Saturne est tellement légère que si on trouvait un océan assez grand, elle pourrait théoriquement flotter !',
              'Saturn is so light that, given a big enough ocean, it could theoretically float!'),
      explain: { simple: T('Saturne porte des anneaux faits de milliards de morceaux de glace.', 'Saturn wears rings made of billions of pieces of ice.'),
                 curious: T('Les anneaux ne font que quelques dizaines de mètres d’épaisseur mais 280 000 km de large.', 'The rings are only tens of metres thick but 280,000 km wide.'),
                 expert: T('Densité moyenne 0,687 g/cm³ < 1. Anneaux : glace d’eau, divisions de Cassini et d’Encke.', 'Mean density 0.687 g/cm³ < 1. Rings: water ice, Cassini and Encke divisions.') } },
    { id: 'uranus', level: 2, kind: 'planet', glyph: '🔵', name: T('Uranus', 'Uranus'), sub: T('Géante de glace', 'Ice giant'),
      color: '#9fd8e0', texture: 'cloud', radius: 7.2, parent: 'sun', orbit: { a: 450, period: 30687 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('2,87 milliards km', '2.87 billion km') },
               { label: T('Diamètre', 'Diameter'), value: T('50 724 km', '50,724 km') },
               { label: T('Température moyenne', 'Average temperature'), value: T('-195 °C', '-195 °C') },
               { label: T('Durée de l’année', 'Year length'), value: T('84 années terrestres', '84 Earth years') } ],
      fact: T('Uranus roule sur le côté : ses saisons durent 21 ans.', 'Uranus rolls on its side: each season lasts 21 years.'),
      explain: { simple: T('Uranus est bleu-vert et couché sur le côté.', 'Uranus is blue-green and lying on its side.'),
                 curious: T('Le méthane de son atmosphère absorbe le rouge, d’où sa couleur.', 'Methane in its atmosphere absorbs red light, giving its colour.'),
                 expert: T('Obliquité 97,8°, probablement due à un impact géant. Manteau d’eau, ammoniac, méthane.', 'Obliquity 97.8°, likely from a giant impact. Water–ammonia–methane mantle.') } },
    { id: 'neptune', level: 2, kind: 'planet', glyph: '🔷', name: T('Neptune', 'Neptune'), sub: T('Géante de glace', 'Ice giant'),
      color: '#4a72c8', texture: 'cloud', radius: 7, parent: 'sun', orbit: { a: 520, period: 60190 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('4,5 milliards km', '4.5 billion km') },
               { label: T('Diamètre', 'Diameter'), value: T('49 244 km', '49,244 km') },
               { label: T('Vents', 'Winds'), value: T('jusqu’à 2 100 km/h', 'up to 2,100 km/h') },
               { label: T('Temps de la lumière', 'Light travel time'), value: T('≈ 4 heures', '≈ 4 hours') } ],
      fact: T('Neptune a les vents les plus violents du Système solaire.', 'Neptune has the fiercest winds in the Solar System.'),
      explain: { simple: T('Neptune est la planète la plus lointaine, très froide et très venteuse.', 'Neptune is the most distant planet: very cold, very windy.'),
                 curious: T('Elle a été trouvée grâce aux mathématiques avant d’être vue au télescope.', 'It was found by mathematics before anyone saw it in a telescope.'),
                 expert: T('Prédiction de Le Verrier, 1846. Flux interne élevé malgré 30 UA de distance.', 'Predicted by Le Verrier in 1846. High internal heat flux despite 30 AU.') } },
    { id: 'pluto', level: 2, kind: 'dwarf', glyph: '🤍', name: T('Pluton', 'Pluto'), sub: T('Planète naine', 'Dwarf planet'),
      color: '#cbb7a4', texture: 'rock', radius: 1.6, parent: 'sun', orbit: { a: 580, period: 90560, tilt: 17 },
      stats: [ { label: T('Distance du Soleil', 'Distance from the Sun'), value: T('5,9 milliards km', '5.9 billion km') },
               { label: T('Diamètre', 'Diameter'), value: T('2 377 km', '2,377 km') },
               { label: T('Température', 'Temperature'), value: T('-229 °C', '-229 °C') } ],
      fact: T('Pluton porte une immense plaine d’azote gelé en forme de cœur.', 'Pluto has a huge heart-shaped plain of frozen nitrogen.'),
      explain: { simple: T('Pluton est une planète naine, plus petite que notre Lune.', 'Pluto is a dwarf planet, smaller than our Moon.'),
                 curious: T('Elle partage son orbite avec d’autres corps de la ceinture de Kuiper.', 'It shares its orbital zone with other Kuiper Belt bodies.'),
                 expert: T('Reclassée en 2006. Résonance 3:2 avec Neptune. Système binaire avec Charon.', 'Reclassified in 2006. 3:2 resonance with Neptune. Binary system with Charon.') } },
    { id: 'halley', level: 2, kind: 'comet', glyph: '☄️', name: T('Comète de Halley', 'Halley’s Comet'), sub: T('Comète périodique', 'Periodic comet'),
      color: '#a8e6ef', radius: 1, parent: 'sun', orbit: { a: 470, period: 27700, tilt: 32, ecc: 0.6 },
      stats: [ { label: T('Retour', 'Next return'), value: T('2061', '2061') },
               { label: T('Période', 'Period'), value: T('76 ans', '76 years') },
               { label: T('Noyau', 'Nucleus'), value: T('15 × 8 km', '15 × 8 km') } ],
      fact: T('Tes arrière-grands-parents et toi pouvez voir la même comète une fois chacun.', 'You and your great-grandparents each get one look at the same comet.'),
      explain: { simple: T('Une comète est une boule de glace et de poussière qui laisse une traînée près du Soleil.', 'A comet is a ball of ice and dust that grows a tail near the Sun.'),
                 curious: T('La queue pointe toujours à l’opposé du Soleil, poussée par le vent solaire.', 'The tail always points away from the Sun, pushed by the solar wind.'),
                 expert: T('Comète rétrograde de la famille de Halley. Deux queues : ions et poussières.', 'Retrograde Halley-type comet. Two tails: ion and dust.') } },

    { id: 'proxima', level: 3, kind: 'star', glyph: '⭐', name: T('Proxima Centauri', 'Proxima Centauri'),
      sub: T('Naine rouge — l’étoile la plus proche', 'Red dwarf — the closest star'),
      color: '#ff7a5c', texture: 'sun', radius: 4, emissive: true,
      stats: [ { label: T('Distance', 'Distance'), value: T('4,24 années-lumière', '4.24 light-years') },
               { label: T('Type', 'Type'), value: T('Naine rouge M5,5', 'M5.5 red dwarf') },
               { label: T('Température', 'Temperature'), value: T('3 042 °C', '3,042 °C') },
               { label: T('Planètes', 'Planets'), value: T('au moins 3', 'at least 3') } ],
      fact: T('Avec la sonde la plus rapide jamais lancée, il faudrait 6 300 ans pour y aller.', 'With our fastest probe, the trip would take 6,300 years.'),
      explain: { simple: T('C’est l’étoile la plus proche de nous après le Soleil.', 'It is the nearest star to us after the Sun.'),
                 curious: T('Trop petite et trop faible pour être vue à l’œil nu, malgré sa proximité.', 'Too small and dim to see with the naked eye, despite being so close.'),
                 expert: T('0,12 M☉. Étoile éruptive UV Ceti, liée gravitationnellement à α Cen AB.', '0.12 M☉. UV Ceti flare star, gravitationally bound to α Cen AB.') } },
    { id: 'sirius', level: 3, kind: 'star', glyph: '✨', name: T('Sirius', 'Sirius'), sub: T('Étoile blanche — la plus brillante du ciel', 'White star — brightest in the sky'),
      color: '#cfe4ff', texture: 'sun', radius: 7, emissive: true,
      stats: [ { label: T('Distance', 'Distance'), value: T('8,6 années-lumière', '8.6 light-years') },
               { label: T('Type', 'Type'), value: T('Étoile blanche A1', 'A1 white star') },
               { label: T('Température', 'Temperature'), value: T('9 665 °C', '9,665 °C') },
               { label: T('Luminosité', 'Luminosity'), value: T('25× le Soleil', '25× the Sun') } ],
      fact: T('Sirius a une petite compagne : une naine blanche grosse comme la Terre.', 'Sirius has a tiny companion: a white dwarf the size of Earth.'),
      explain: { simple: T('Sirius est l’étoile la plus brillante que tu peux voir la nuit.', 'Sirius is the brightest star you can see at night.'),
                 curious: T('Elle scintille de toutes les couleurs quand elle est basse sur l’horizon.', 'It flickers in many colours when low on the horizon.'),
                 expert: T('Système binaire A/B. Magnitude apparente -1,46. Sirius B : 0,98 M☉ en 0,0084 R☉.', 'A/B binary. Apparent magnitude -1.46. Sirius B: 0.98 M☉ in 0.0084 R☉.') } },
    { id: 'betelgeuse', level: 3, kind: 'star', glyph: '🔶', name: T('Bételgeuse', 'Betelgeuse'), sub: T('Supergéante rouge', 'Red supergiant'),
      color: '#ff6a4a', texture: 'sun', radius: 13, emissive: true,
      stats: [ { label: T('Distance', 'Distance'), value: T('550 années-lumière', '550 light-years') },
               { label: T('Diamètre', 'Diameter'), value: T('≈ 1 200× le Soleil', '≈ 1,200× the Sun') },
               { label: T('Âge', 'Age'), value: T('8 à 10 millions d’années', '8–10 million years') },
               { label: T('Avenir', 'Future'), value: T('supernova', 'supernova') } ],
      fact: T('À la place du Soleil, Bételgeuse engloutirait l’orbite de Jupiter.', 'Placed at the Sun, Betelgeuse would swallow Jupiter’s orbit.'),
      explain: { simple: T('Bételgeuse est une étoile géante en fin de vie qui explosera un jour.', 'Betelgeuse is a giant star near the end of its life; one day it will explode.'),
                 curious: T('Tu la vois telle qu’elle était il y a 550 ans : elle a peut-être déjà explosé.', 'You see it as it was 550 years ago — it may already have exploded.'),
                 expert: T('M1-2 Ia-ab, ≈ 16,5 M☉. Grand assombrissement de 2019-2020 dû à un nuage de poussière.', 'M1-2 Ia-ab, ≈ 16.5 M☉. The 2019–20 Great Dimming came from an ejected dust cloud.') } },
    { id: 'vega', level: 3, kind: 'star', glyph: '⭐', name: T('Véga', 'Vega'), sub: T('Étoile blanc-bleu', 'Blue-white star'),
      color: '#d8e8ff', texture: 'sun', radius: 6, emissive: true,
      stats: [ { label: T('Distance', 'Distance'), value: T('25 années-lumière', '25 light-years') },
               { label: T('Type', 'Type'), value: T('A0 V', 'A0 V') },
               { label: T('Rotation', 'Rotation'), value: T('12,5 heures', '12.5 hours') } ],
      fact: T('Véga tourne si vite qu’elle est aplatie comme un ballon écrasé.', 'Vega spins so fast it is squashed like a flattened ball.'),
      explain: { simple: T('Véga est une étoile très brillante et très bleue.', 'Vega is a very bright, very blue star.'),
                 curious: T('Elle a servi longtemps de référence pour mesurer la brillance des étoiles.', 'It long served as the reference point for measuring stellar brightness.'),
                 expert: T('Vitesse équatoriale 236 km/s, 88 % de la rupture. Disque de débris détecté à 12 μm.', 'Equatorial velocity 236 km/s, 88% of breakup. Debris disc detected at 12 μm.') } },

    { id: 'orion', level: 4, kind: 'nebula', glyph: '🌫', name: T('Nébuleuse d’Orion', 'Orion Nebula'),
      sub: T('Pouponnière d’étoiles', 'Stellar nursery'), color: '#8b6cff', palette: ['#ff7bb0', '#7b8cff', '#63e6ff'],
      stats: [ { label: T('Distance', 'Distance'), value: T('1 344 années-lumière', '1,344 light-years') },
               { label: T('Largeur', 'Width'), value: T('24 années-lumière', '24 light-years') },
               { label: T('Étoiles en formation', 'Forming stars'), value: T('plus de 700', 'more than 700') } ],
      fact: T('C’est une des rares nébuleuses visibles à l’œil nu depuis la Terre.', 'It is one of the few nebulae visible to the naked eye from Earth.'),
      explain: { simple: T('Une nébuleuse est un immense nuage de gaz où naissent des étoiles.', 'A nebula is a huge cloud of gas where stars are born.'),
                 curious: T('La gravité comprime le gaz en grumeaux qui s’allument et deviennent des étoiles.', 'Gravity squeezes the gas into clumps that ignite and become stars.'),
                 expert: T('Région H II, M42. Amas du Trapèze, disques protoplanétaires photo-évaporés.', 'H II region, M42. Trapezium cluster, photo-evaporating protoplanetary discs.') } },
    { id: 'crab', level: 4, kind: 'nebula', glyph: '🦀', name: T('Nébuleuse du Crabe', 'Crab Nebula'), sub: T('Rémanent de supernova', 'Supernova remnant'),
      color: '#63e6ff', palette: ['#63e6ff', '#a06bff', '#ffd166'],
      stats: [ { label: T('Distance', 'Distance'), value: T('6 500 années-lumière', '6,500 light-years') },
               { label: T('Explosion observée', 'Explosion seen'), value: T('en 1054', 'in 1054') },
               { label: T('Au centre', 'At the centre'), value: T('un pulsar', 'a pulsar') } ],
      fact: T('Des astronomes chinois ont vu cette explosion en 1054, visible en plein jour.', 'Chinese astronomers saw this explosion in 1054 — visible in daylight.'),
      explain: { simple: T('C’est ce qui reste d’une étoile qui a explosé il y a très longtemps.', 'It is what remains of a star that exploded long ago.'),
                 curious: null, expert: null },
      explainOverride: {
        curious: T('Le gaz s’écarte encore à 1 500 km/s, éclairé par l’étoile à neutrons du centre.', 'The gas is still expanding at 1,500 km/s, lit by the neutron star at its centre.'),
        expert: T('SN 1054, rémanent pulsar-wind. PSR B0531+21, période 33 ms.', 'SN 1054, pulsar-wind remnant. PSR B0531+21, 33 ms period.') } },
    { id: 'sgra', level: 4, kind: 'blackhole', glyph: '🕳', name: T('Sagittarius A*', 'Sagittarius A*'),
      sub: T('Trou noir supermassif', 'Supermassive black hole'), color: '#ffb35c', jets: false,
      stats: [ { label: T('Emplacement', 'Location'), value: T('centre de la Voie lactée', 'centre of the Milky Way') },
               { label: T('Masse', 'Mass'), value: T('≈ 4 millions de Soleils', '≈ 4 million Suns') },
               { label: T('Distance', 'Distance'), value: T('≈ 26 000 années-lumière', '≈ 26,000 light-years') },
               { label: T('Horizon des événements', 'Event horizon'), value: T('≈ 24 millions km', '≈ 24 million km') } ],
      fact: T('Sa première image a été publiée en 2022, après des années de calcul.', 'Its first image was published in 2022, after years of computation.'),
      warning: T('Zone extrême', 'Extreme zone'),
      limit: T('Plus près, même la lumière ne pourrait plus revenir !', 'Any closer and even light could never come back!'),
      explain: { simple: T('Un trou noir est une région de l’espace où la gravité est tellement forte que même la lumière ne peut plus s’échapper.',
                          'A black hole is a region of space where gravity is so strong that not even light can escape.'),
                 curious: T('On ne voit pas le trou noir lui-même, seulement le gaz brûlant qui tourne autour et la lumière déformée derrière.',
                            'You never see the black hole itself — only the hot gas swirling around it and the light bent behind it.'),
                 expert: T('Rayon de Schwarzschild ≈ 1,2×10¹⁰ m. Disque d’accrétion, horizon des événements, lentille gravitationnelle relativiste.',
                           'Schwarzschild radius ≈ 1.2×10¹⁰ m. Accretion disc, event horizon, relativistic gravitational lensing.') } },
    { id: 'cygnusx1', level: 4, kind: 'blackhole', glyph: '🕳', name: T('Cygnus X-1', 'Cygnus X-1'),
      sub: T('Trou noir stellaire', 'Stellar-mass black hole'), color: '#9fd0ff', jets: true,
      stats: [ { label: T('Distance', 'Distance'), value: T('≈ 7 200 années-lumière', '≈ 7,200 light-years') },
               { label: T('Masse', 'Mass'), value: T('≈ 21 Soleils', '≈ 21 Suns') },
               { label: T('Compagne', 'Companion'), value: T('une supergéante bleue', 'a blue supergiant') },
               { label: T('Découverte', 'Discovered'), value: T('1964', '1964') } ],
      fact: T('Il aspire le gaz de son étoile compagne, ce qui le rend brillant en rayons X.',
              'It pulls gas from its companion star, making it shine brightly in X-rays.'),
      warning: T('Zone extrême', 'Extreme zone'),
      limit: T('Plus près, même la lumière ne pourrait plus revenir !', 'Any closer and even light could never come back!'),
      explain: { simple: T('Cygnus X-1 est un trou noir né de la mort d’une étoile très massive.', 'Cygnus X-1 is a black hole born from the death of a very massive star.'),
                 curious: T('C’est le premier trou noir que les astronomes ont réussi à identifier avec certitude.', 'It was the first black hole astronomers managed to identify with confidence.'),
                 expert: T('Binaire X à forte masse HDE 226868. Spin proche de la limite de Kerr.', 'High-mass X-ray binary HDE 226868. Spin close to the Kerr limit.') } },
    { id: 'm87', level: 5, kind: 'blackhole', glyph: '🕳', name: T('M87*', 'M87*'),
      sub: T('Trou noir supermassif — premier photographié', 'Supermassive black hole — first ever imaged'), color: '#ffb35c', jets: true,
      stats: [ { label: T('Emplacement', 'Location'), value: T('galaxie M87', 'galaxy M87') },
               { label: T('Masse', 'Mass'), value: T('6,5 milliards de Soleils', '6.5 billion Suns') },
               { label: T('Distance', 'Distance'), value: T('≈ 55 millions années-lumière', '≈ 55 million light-years') },
               { label: T('Image', 'Image'), value: T('publiée en 2019', 'published in 2019') } ],
      fact: T('Son jet de matière s’étend sur 5 000 années-lumière hors de sa galaxie.',
              'Its jet of matter stretches 5,000 light-years out of its galaxy.'),
      warning: T('Zone extrême', 'Extreme zone'),
      limit: T('Plus près, même la lumière ne pourrait plus revenir !', 'Any closer and even light could never come back!'),
      explain: { simple: T('C’est le premier trou noir dont on a pris une véritable photo.', 'It is the first black hole ever truly photographed.'),
                 curious: T('Huit radiotélescopes de la planète ont travaillé ensemble comme un seul télescope géant.', 'Eight radio telescopes across the planet worked together as one giant telescope.'),
                 expert: T('Interférométrie VLBI à 1,3 mm (EHT). Ombre de 42 μas, jet relativiste HST-1.', 'VLBI interferometry at 1.3 mm (EHT). 42 μas shadow, HST-1 relativistic jet.') } },
    { id: 'vela', level: 4, kind: 'pulsar', glyph: '📡', name: T('Pulsar de Vela', 'Vela Pulsar'), sub: T('Étoile à neutrons en rotation', 'Rotating neutron star'),
      color: '#9fd0ff',
      stats: [ { label: T('Distance', 'Distance'), value: T('959 années-lumière', '959 light-years') },
               { label: T('Rotation', 'Rotation'), value: T('11 tours par seconde', '11 turns per second') },
               { label: T('Diamètre', 'Diameter'), value: T('≈ 20 km', '≈ 20 km') },
               { label: T('Masse', 'Mass'), value: T('1,4 Soleil', '1.4 Suns') } ],
      fact: T('Certains pulsars tournent plusieurs centaines de fois par seconde.', 'Some pulsars spin several hundred times per second.'),
      explain: { simple: T('Un pulsar est une étoile morte minuscule qui tourne très vite et envoie deux faisceaux comme un phare.',
                          'A pulsar is a tiny dead star spinning very fast, sweeping two beams like a lighthouse.'),
                 curious: T('Une cuillère de sa matière pèserait autant qu’une montagne.', 'A spoonful of its material would weigh as much as a mountain.'),
                 expert: T('PSR B0833-45. Émission radio dipolaire, glitches de rotation observés.', 'PSR B0833-45. Dipolar radio emission, observed rotation glitches.') } },
    { id: 'trappist', level: 3, kind: 'exo', glyph: '🌱', name: T('TRAPPIST-1e', 'TRAPPIST-1e'), sub: T('Exoplanète rocheuse', 'Rocky exoplanet'),
      color: '#7fc6a8', habitable: true,
      stats: [ { label: T('Distance', 'Distance'), value: T('40 années-lumière', '40 light-years') },
               { label: T('Taille', 'Size'), value: T('0,92× la Terre', '0.92× Earth') },
               { label: T('Masse', 'Mass'), value: T('0,69× la Terre', '0.69× Earth') },
               { label: T('Température estimée', 'Estimated temperature'), value: T('≈ -22 °C', '≈ -22 °C') },
               { label: T('Étoile', 'Star'), value: T('naine rouge TRAPPIST-1', 'red dwarf TRAPPIST-1') },
               { label: T('Zone habitable', 'Habitable zone'), value: T('oui', 'yes') } ],
      fact: T('Son système compte sept planètes rocheuses serrées autour d’une petite étoile rouge.', 'Its system holds seven rocky planets packed around a small red star.'),
      explain: { simple: T('Une exoplanète est une planète qui tourne autour d’une autre étoile que le Soleil.', 'An exoplanet is a planet orbiting a star other than the Sun.'),
                 curious: T('Elle est dans la zone où l’eau liquide serait possible — on ne sait pas si la vie y existe.', 'It sits where liquid water could exist — we do not know whether life is there.'),
                 expert: T('Transit détecté par TRAPPIST/Spitzer. Probablement en rotation synchrone.', 'Transit detected by TRAPPIST/Spitzer. Likely tidally locked.') } },
    { id: 'milkyway', level: 4, kind: 'galaxy', glyph: '🌌', name: T('Voie lactée', 'Milky Way'), sub: T('Galaxie spirale barrée', 'Barred spiral galaxy'),
      color: '#bcd0ff',
      stats: [ { label: T('Diamètre', 'Diameter'), value: T('100 000 années-lumière', '100,000 light-years') },
               { label: T('Étoiles', 'Stars'), value: T('200 à 400 milliards', '200–400 billion') },
               { label: T('Notre position', 'Our position'), value: T('bras d’Orion, à 26 000 al du centre', 'Orion Arm, 26,000 ly from the centre') },
               { label: T('Un tour du Soleil', 'One solar orbit'), value: T('230 millions d’années', '230 million years') } ],
      fact: T('Depuis notre place dans la galaxie, le Soleil n’est qu’un point parmi des centaines de milliards.',
              'From our place in the galaxy, the Sun is one dot among hundreds of billions.'),
      explain: { simple: T('Notre galaxie est un immense tourbillon d’étoiles, et nous sommes dedans.', 'Our galaxy is a giant whirlpool of stars, and we are inside it.'),
                 curious: T('La bande blanche visible la nuit d’été, c’est notre galaxie vue de l’intérieur.', 'The white band you see on summer nights is our galaxy seen from within.'),
                 expert: T('Type SBc. Halo de matière noire ≈ 1,5×10¹² M☉. Trou noir central Sgr A*.', 'Type SBc. Dark matter halo ≈ 1.5×10¹² M☉. Central black hole Sgr A*.') } },
    { id: 'andromeda', level: 5, kind: 'galaxy', glyph: '🌌', name: T('Andromède', 'Andromeda'), sub: T('Galaxie spirale — M31', 'Spiral galaxy — M31'),
      color: '#cbb6ff',
      stats: [ { label: T('Distance', 'Distance'), value: T('2,5 millions d’années-lumière', '2.5 million light-years') },
               { label: T('Étoiles', 'Stars'), value: T('≈ 1 000 milliards', '≈ 1 trillion') },
               { label: T('Rencontre avec nous', 'Meeting with us'), value: T('dans 4,5 milliards d’années', 'in 4.5 billion years') } ],
      fact: T('Andromède et la Voie lactée fusionneront un jour en une seule galaxie.', 'Andromeda and the Milky Way will one day merge into a single galaxy.'),
      explain: { simple: T('Andromède est la grande galaxie voisine de la nôtre.', 'Andromeda is the big galaxy next door to ours.'),
                 curious: T('C’est l’objet le plus lointain visible à l’œil nu.', 'It is the most distant object visible to the naked eye.'),
                 expert: T('Approche à 110 km/s. Fusion en galaxie elliptique « Lactomède ».', 'Approaching at 110 km/s. Merger into the elliptical “Milkomeda”.') } },
    { id: 'cosmicweb', level: 6, kind: 'structure', glyph: '🕸', name: T('La toile cosmique', 'The cosmic web'), sub: T('Plus grande structure connue', 'Largest known structure'),
      color: '#8fb6ff',
      stats: [ { label: T('Échelle', 'Scale'), value: T('des milliards d’années-lumière', 'billions of light-years') },
               { label: T('Galaxies', 'Galaxies'), value: T('des centaines de milliards', 'hundreds of billions') },
               { label: T('Vides cosmiques', 'Cosmic voids'), value: T('jusqu’à 300 millions d’al', 'up to 300 million ly') } ],
      fact: T('À très grande échelle, les galaxies forment une gigantesque structure ressemblant à un réseau.',
              'On the largest scales, galaxies form a gigantic network-like structure.'),
      explain: { simple: T('Les galaxies ne sont pas éparpillées au hasard : elles forment des fils et des murs.', 'Galaxies are not scattered at random: they form threads and walls.'),
                 curious: T('Entre les filaments s’étendent d’immenses vides presque sans galaxies.', 'Between the filaments lie vast voids almost empty of galaxies.'),
                 expert: T('Croissance des structures par instabilité gravitationnelle depuis les fluctuations du CMB.', 'Structure growth by gravitational instability from CMB fluctuations.') } }
  ];

  /* fix the one entry authored with an override block */
  const crab = BODIES.find(b => b.id === 'crab');
  crab.explain = { simple: crab.explain.simple, curious: crab.explainOverride.curious, expert: crab.explainOverride.expert };
  delete crab.explainOverride;

  /* ---------- missions (§23-24) ---------- */
  const MISSIONS = [
    { id: 'm01', num: '01', title: T('Notre voisinage spatial', 'Our space neighbourhood'),
      reward: T('🏅 Explorateur du Système solaire', '🏅 Solar System Explorer'),
      objectives: [
        { id: 'o1', body: 'earth',   label: T('Quitter la Terre', 'Leave Earth'), done: true },
        { id: 'o2', body: 'moon',    label: T('Trouver la Lune', 'Find the Moon'), done: true },
        { id: 'o3', body: 'mars',    label: T('Visiter Mars', 'Visit Mars'), done: false },
        { id: 'o4', body: 'jupiter', label: T('Observer Jupiter', 'Observe Jupiter'), done: false },
        { id: 'o5', body: 'saturn',  label: T('Trouver les anneaux de Saturne', 'Find Saturn’s rings'), done: false }
      ] },
    { id: 'm02', num: '02', title: T('Les géantes', 'The giants'), reward: T('🏅 Ami des géantes', '🏅 Friend of Giants'),
      objectives: [
        { id: 'o1', body: 'jupiter', label: T('Jupiter', 'Jupiter'), done: false },
        { id: 'o2', body: 'saturn',  label: T('Saturne', 'Saturn'), done: false },
        { id: 'o3', body: 'uranus',  label: T('Uranus', 'Uranus'), done: false },
        { id: 'o4', body: 'neptune', label: T('Neptune', 'Neptune'), done: false }
      ] },
    { id: 'm03', num: '03', title: T('Voyage vers une étoile', 'Journey to a star'), reward: T('🏅 Marcheur d’étoiles', '🏅 Star Walker'),
      objectives: [
        { id: 'o1', body: 'sun',     label: T('Observer le Soleil de près', 'Watch the Sun up close'), done: false },
        { id: 'o2', body: 'proxima', label: T('Atteindre Proxima Centauri', 'Reach Proxima Centauri'), done: false }
      ] },
    { id: 'm04', num: '04', title: T('Mystères de l’espace', 'Mysteries of space'), reward: T('🏅 Chasseur de mystères', '🏅 Mystery Hunter'),
      objectives: [
        { id: 'o1', body: 'vela',   label: T('Trouver un pulsar', 'Find a pulsar'), done: false },
        { id: 'o2', body: 'orion',  label: T('Trouver une nébuleuse', 'Find a nebula'), done: false },
        { id: 'o3', body: 'crab',   label: T('Trouver une supernova', 'Find a supernova'), done: false },
        { id: 'o4', body: 'sgra',   label: T('Observer un trou noir', 'Observe a black hole'), done: false }
      ] }
  ];

  /* ---------- size comparator (§13, §31) ---------- */
  const COMPARISONS = [
    { id: 'earth-jupiter', pair: ['earth', 'jupiter'], sizes: [12742, 139820], color: ['#3f8fd6', '#d9a06a'],
      caption: T('Jupiter pourrait contenir environ 1 300 Terres.', 'Jupiter could hold about 1,300 Earths.') },
    { id: 'jupiter-sun', pair: ['jupiter', 'sun'], sizes: [139820, 1392000], color: ['#d9a06a', '#ffcf6b'],
      caption: T('Le Soleil est 10 fois plus large que Jupiter.', 'The Sun is 10 times wider than Jupiter.') },
    { id: 'sun-betelgeuse', pair: ['sun', 'betelgeuse'], sizes: [1392000, 1670000000], color: ['#ffcf6b', '#ff6a4a'],
      caption: T('Bételgeuse est environ 1 200 fois plus large que le Soleil.', 'Betelgeuse is about 1,200 times wider than the Sun.') }
  ];

  /* ---------- light travel times (§30) ---------- */
  const LIGHT_TRIPS = [
    { to: T('Lune', 'Moon'), time: T('1,3 seconde', '1.3 seconds'), w: 2 },
    { to: T('Soleil', 'Sun'), time: T('8 min 20 s', '8 min 20 s'), w: 12 },
    { to: T('Neptune', 'Neptune'), time: T('≈ 4 heures', '≈ 4 hours'), w: 28 },
    { to: T('Proxima Centauri', 'Proxima Centauri'), time: T('4,24 ans', '4.24 years'), w: 55 },
    { to: T('Andromède', 'Andromeda'), time: T('≈ 2,5 millions d’années', '≈ 2.5 million years'), w: 100 }
  ];

  /* ---------- explorer profile (§25) ---------- */
  const PROFILE = {
    name: 'Lina', level: 7,
    counts: [
      { label: T('planètes découvertes', 'planets discovered'), value: 12 },
      { label: T('étoiles découvertes', 'stars discovered'), value: 24 },
      { label: T('galaxies visitées', 'galaxies visited'), value: 3 },
      { label: T('trou noir observé', 'black hole observed'), value: 1 }
    ],
    discovered: ['earth', 'moon', 'iss', 'sun', 'mars', 'saturn', 'sirius', 'andromeda'],
    badges: [
      { glyph: '🏅', label: T('Explorateur du Système solaire', 'Solar System Explorer') },
      { glyph: '🕳', label: T('Premier trou noir', 'First black hole') },
      { glyph: '🌌', label: T('Voyageur de galaxies', 'Galaxy traveller') }
    ]
  };

  /* ---------- NOVA lines (§28) ---------- */
  const NOVA = {
    earth: T('Tu vois cette fine ligne bleue ? C’est tout l’air que nous avons. Prêt à partir ?',
             'See that thin blue line? That is all the air we have. Ready to go?'),
    solar: T('Huit planètes tournent autour du Soleil. Laquelle veux-tu visiter en premier ?',
             'Eight planets circle the Sun. Which one do you want to visit first?'),
    mars: T('Tu vois cette planète rouge ? C’est Mars ! Veux-tu savoir pourquoi elle est rouge ?',
            'See that red planet? That is Mars! Want to know why it is red?'),
    saturn: T('Regarde bien les anneaux : ils sont faits de milliards de morceaux de glace.',
              'Look closely at the rings: they are made of billions of pieces of ice.'),
    sgra: T('Nous nous arrêtons ici. Plus près, même la lumière ne pourrait plus revenir.',
            'We stop here. Any closer and even light could never come back.'),
    galaxy: T('Cette petite flèche, c’est nous. Tout ce que tu connais tient dans ce point.',
              'That little arrow is us. Everything you know fits inside that dot.'),
    universe: T('Tu viens de voyager de ta maison jusqu’aux limites de l’Univers observable. Et pourtant… il nous reste énormément de choses à découvrir.',
                'You have travelled from your home to the edge of the observable universe. And still… there is so much left to find.')
  };

  /* ---------- UI copy ---------- */
  const UI = {
    brand: T('COSMOS KIDS', 'COSMOS KIDS'),
    nav: [ T('Explorer', 'Explore'), T('Missions', 'Missions'), T('Découvertes', 'Discoveries'), T('Mes collections', 'My collections') ],
    landingTitle: T(['L’Univers est immense.', 'À toi de l’explorer.'], ['The Universe is immense.', 'Yours to explore.']),
    landingText: T('Voyage depuis la Terre jusqu’aux confins de l’Univers. Découvre les planètes, les étoiles, les galaxies, les trous noirs et les plus grands mystères du cosmos.',
                   'Travel from Earth to the edge of the Universe. Discover planets, stars, galaxies, black holes and the greatest mysteries of the cosmos.'),
    ctaPrimary: T('🚀 Commencer depuis la Terre', '🚀 Start from Earth'),
    ctaSecondary: T('🌌 Explorer l’Univers', '🌌 Explore the Universe'),
    earthTitle: T('Ton voyage commence ici.', 'Your journey starts here.'),
    earthSub: T('Voici notre maison : la Terre. Mais qu’y a-t-il après le ciel ?', 'This is our home: Earth. But what lies beyond the sky?'),
    earthCta: T('🚀 Commencer l’exploration', '🚀 Start exploring'),
    earthCta2: T('Explorer librement', 'Explore freely'),
    searchPlaceholder: T('Cherche une planète, une étoile ou une galaxie…', 'Search for a planet, a star or a galaxy…'),
    searchHint: T('Essaie : Mars · Saturne · trou noir · Andromède · TRAPPIST-1', 'Try: Mars · Saturn · black hole · Andromeda · TRAPPIST-1'),
    noResult: T('Rien trouvé. Essaie « trou noir » ou « Saturne ».', 'Nothing found. Try “black hole” or “Saturn”.'),
    didYouKnow: T('🤯 Le savais-tu ?', '🤯 Did you know?'),
    explainMe: T('🧠 Explique-moi', '🧠 Explain it to me'),
    levelsExplain: [ T('👶 Simple', '👶 Simple'), T('🧒 Curieux', '🧒 Curious'), T('🔬 Expert', '🔬 Expert') ],
    travelTo: T('🚀 Voyager vers', '🚀 Travel to'),
    explore: T('🔍 Explorer', '🔍 Explore'),
    addToFinds: T('⭐ Ajouter à mes découvertes', '⭐ Add to my discoveries'),
    listen: T('🎧 Écouter l’histoire', '🎧 Listen to the story'),
    destination: T('Destination', 'Destination'),
    distance: T('Distance', 'Distance'),
    arrival: T('Arrivée sur', 'Arrived at'),
    clickToDiscover: T('Cliquer pour découvrir', 'Click to discover'),
    display: T('👁 Affichage', '👁 Display'),
    toggles: [ T('Orbites', 'Orbits'), T('Noms', 'Names'), T('Trajectoires', 'Trails'), T('Distances', 'Distances'), T('Échelle', 'Scale') ],
    youAreHere: T('Nous sommes ici', 'We are here'),
    scaleTitle: T('📏 Du plus petit au plus grand', '📏 From smallest to largest'),
    compareTitle: T('Comparer', 'Compare'),
    freeMode: T('🌌 Exploration libre', '🌌 Free exploration'),
    exitFree: T('Quitter le mode libre', 'Leave free mode'),
    back: T('Retour', 'Back'),
    simplified: T('Distances réduites pour faciliter l’exploration.', 'Distances reduced to make exploring easier.'),
    lookingBack: T('👀 Tu regardes dans le passé.', '👀 You are looking into the past.'),
    lightSpeedTitle: T('Voyage à la vitesse de la lumière', 'Travelling at the speed of light'),
    missionLabel: T('Mission', 'Mission'),
    reward: T('Récompense', 'Reward'),
    ultimateTitle: T('Jusqu’où peut-on regarder ?', 'How far can we see?'),
    ultimateText: T('Voici l’Univers observable. Nous ne savons pas encore ce qui existe au-delà de ce que la lumière a eu le temps de nous montrer.',
                    'This is the observable Universe. We still do not know what lies beyond what light has had time to show us.'),
    continueCta: T('🔭 Continuer à explorer', '🔭 Keep exploring'),
    homeCta: T('🌍 Retourner sur Terre', '🌍 Return to Earth'),
    welcomeHome: T('Bienvenue chez toi. 🌍', 'Welcome home. 🌍'),
    welcomeHomeSub: T('Dans l’immensité de l’Univers, cette petite planète est notre maison.',
                      'In the immensity of the Universe, this small planet is our home.'),
    newDiscovery: T('✨ Nouvelle découverte', '✨ New discovery'),
    hint: T('Glisse pour tourner · Molette pour zoomer · Double-clic pour voyager',
            'Drag to rotate · Scroll to zoom · Double-click to travel'),
    observing: T('Observer le trou noir', 'Observe the black hole'),
    kinds: {
      planet: T('Planète', 'Planet'), moon: T('Lune', 'Moon'), star: T('Étoile', 'Star'), dwarf: T('Planète naine', 'Dwarf planet'),
      comet: T('Comète', 'Comet'), nebula: T('Nébuleuse', 'Nebula'), blackhole: T('Trou noir', 'Black hole'),
      pulsar: T('Pulsar', 'Pulsar'), exo: T('Exoplanète', 'Exoplanet'), galaxy: T('Galaxie', 'Galaxy'),
      structure: T('Structure', 'Structure'), station: T('Station', 'Station')
    }
  };

  const DATA = { LEVELS, BODIES, MISSIONS, COMPARISONS, LIGHT_TRIPS, PROFILE, NOVA, UI };
  root.COSMOS_DATA = DATA;
  root.dispatchEvent && root.dispatchEvent(new Event('cosmos-data-ready'));
  if (typeof module !== 'undefined') module.exports = DATA;
})(typeof window !== 'undefined' ? window : globalThis);
